# Generated by Django 2.0.1 on 2018-01-28 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_profile_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='ocation',
            field=models.CharField(max_length=120, null=True),
        ),
    ]
