# Generated by Django 2.0.1 on 2018-01-28 23:26

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('profiles', '0004_profile_ocation'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='ocation',
            new_name='job',
        ),
    ]
